ORIGIN="远控Pro官方源"
LABEL="远控Pro官方源"
DESCRIPTION="全场景设备智控方案"
SITE_URL="https://remotepro.cn"
AUTHOR_FROM="YKP"
AUTHOR_TO="全场景设备智控方案"
ICON_FROM="file:///Applications/YKApp.app/AppIcon60x60@2x.png"
CYDIA_PACKAGE="com.sky.ykpro"
